### ISSUE TITLE
how to use it with yamcs ?

### ISSUE THREAD

**Issue by Amr-Abdelaziz** [yamcs/jsle#1]

**Comment by xpromache** [comment]
Not possible for the moment. I left SLE a bit on the side because we don't need it for the moment but if you want to test it I think I can have something working in a week or two.
Which SLE service do you need?

**Comment by Amr-Abdelaziz** [comment]
Return All frames Service

**Comment by xpromache** [comment]
The "one week or two" turned into a month but now I finally had a little time to make it work.
Please try to follow the steps described here:
https://github.com/yamcs/yamcs-sle/blob/master/README.md

and let me know how it works. 

I only tested it with an old SLE library from ESA.

**Comment by Amr-Abdelaziz** [comment]
Well Done
But as i understand you tested it with another ESA SLE library not this.
So for me YAMCS is working now but with status unavailable (no telemetry).
How can i have a full simulation scenario?
Thanks

**Comment by Amr-Abdelaziz** [comment]
To be more clear what is the possibility of using  YAMCS for the prototyping of CCSDS Space data link Security protocol?

**Comment by xpromache** [comment]
> Well Done
> But as i understand you tested it with another ESA SLE library not this.
> So for me YAMCS is working now but with status unavailable (no telemetry).
> How can i have a full simulation scenario?
> Thanks

Currently Yamcs can be used as a client to a SLE provider (typically a ground station). 
I thought you already have a provider to which you want to connect.
To simulate a full scenario with Yamcs, it will require implementing the provider part. This is not top priority for the moment.

> To be more clear what is the possibility of using YAMCS for the prototyping of CCSDS Space data link > Security protocol?

I'm not very familiar with this protocol (just spent 10 minutes to educate myself) but I understand that you have to encrypt the data inside the frame (the headers are not encrypted for compatibility with old applications) . It doesn't sound very difficult to implement as there is no complicated handshake or negotiation mechanism. But the standard does not specify which algorithms to use so it depends on the mission. 

As far as I can see, this is independent from SLE because SLE is used to transfer frames from the ground stations to the control center (or another application) encrypted or not. You can as well use UDP for transferring the frames if it's just for prototyping purposes.

What are your exact requirements?

**Comment by Amr-Abdelaziz** [comment]
"I thought you already have a provider to which you want to connect." unfortunately i don't have the provider part So i will use UDP
Thanks for your time

**Comment by xpromache** [comment]
> "I thought you already have a provider to which you want to connect." unfortunately i don't have the provider part So i will use UDP
> Thanks for your time

Without a provider, I don't see why you are interested in SLE - it's not the most easy to work protocol. If you want just to experiment, plain UDP is much easier.
